/**
 * Captures the current Alpine demo company state and writes it to
 * lib/demo/alpine-snapshot.ts for use by the demo reset endpoint.
 *
 * Run:
 *   npx tsx --env-file=.env.local scripts/capture-alpine-snapshot.ts
 *
 * Safe: read-only — never mutates the database.
 * Re-runnable: overwrites the snapshot file each time.
 */

import { createClient } from '@supabase/supabase-js'
import { mkdirSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const COMPANY_ID = 'aa8c5a35-8c06-4dee-8c13-7b3523f549d2'
const OUT_PATH = resolve(__dirname, '../lib/demo/alpine-snapshot.ts')

function requireEnv(name: string): string {
  const v = process.env[name]
  if (!v) throw new Error(`Missing env var: ${name}`)
  return v
}

function assertOk(name: string, error: { message: string } | null) {
  if (error) throw new Error(`Query failed [${name}]: ${error.message}`)
}

async function main() {
  const supabase = createClient(
    requireEnv('NEXT_PUBLIC_SUPABASE_URL'),
    requireEnv('SUPABASE_SERVICE_ROLE_KEY'),
    { auth: { persistSession: false } },
  )

  console.log(`Capturing Alpine snapshot  (company: ${COMPANY_ID})\n`)

  // ── Phase 1: tables with a direct company_id column ──────────────────────

  const [
    bookingsRes,
    instancesRes,
    blocksRes,
    feedbackRes,
    vehiclesRes,
    settingsRes,
  ] = await Promise.all([
    supabase.from('bookings').select('*').eq('company_id', COMPANY_ID).limit(5000),
    supabase.from('checklist_instances').select('*').eq('company_id', COMPANY_ID).limit(5000),
    supabase.from('vehicle_blocks').select('*').eq('company_id', COMPANY_ID).limit(5000),
    supabase.from('guest_feedback').select('*').eq('company_id', COMPANY_ID).limit(5000),
    supabase.from('vehicles').select('*').eq('company_id', COMPANY_ID).limit(5000),
    supabase.from('company_settings').select('*').eq('id', COMPANY_ID).limit(1),
  ])

  assertOk('bookings',           bookingsRes.error)
  assertOk('checklist_instances', instancesRes.error)
  assertOk('vehicle_blocks',     blocksRes.error)
  assertOk('guest_feedback',     feedbackRes.error)
  assertOk('vehicles',           vehiclesRes.error)
  assertOk('company_settings',   settingsRes.error)

  const instanceIds = (instancesRes.data ?? []).map((r) => r.id as string)
  const vehicleIds  = (vehiclesRes.data ?? []).map((r) => r.id as string)

  console.log(`  bookings              : ${bookingsRes.data?.length ?? 0}`)
  console.log(`  checklist_instances   : ${instancesRes.data?.length ?? 0}`)
  console.log(`  vehicle_blocks        : ${blocksRes.data?.length ?? 0}`)
  console.log(`  guest_feedback        : ${feedbackRes.data?.length ?? 0}`)
  console.log(`  vehicles              : ${vehiclesRes.data?.length ?? 0}`)
  console.log(`  company_settings      : ${settingsRes.data?.length ?? 0}`)

  // ── Phase 2: tables with no direct company_id — join via parent IDs ───────

  const empty = { data: [] as unknown[], error: null }

  const [itemsRes, historyRes, complianceRes, issuesRes] = await Promise.all([
    instanceIds.length > 0
      ? supabase.from('checklist_instance_items').select('*').in('instance_id', instanceIds).limit(50000)
      : Promise.resolve(empty),
    instanceIds.length > 0
      ? supabase.from('checklist_reopen_history').select('*').in('checklist_instance_id', instanceIds).limit(5000)
      : Promise.resolve(empty),
    vehicleIds.length > 0
      ? supabase.from('vehicle_compliance').select('*').in('vehicle_id', vehicleIds).limit(5000)
      : Promise.resolve(empty),
    vehicleIds.length > 0
      ? supabase.from('vehicle_issues').select('*').in('vehicle_id', vehicleIds).limit(5000)
      : Promise.resolve(empty),
  ])

  assertOk('checklist_instance_items',  itemsRes.error)
  assertOk('checklist_reopen_history',  historyRes.error)
  assertOk('vehicle_compliance',        complianceRes.error)
  assertOk('vehicle_issues',            issuesRes.error)

  console.log(`  checklist_instance_items  : ${itemsRes.data?.length ?? 0}`)
  console.log(`  checklist_reopen_history  : ${historyRes.data?.length ?? 0}`)
  console.log(`  vehicle_compliance        : ${complianceRes.data?.length ?? 0}`)
  console.log(`  vehicle_issues            : ${issuesRes.data?.length ?? 0}`)

  // ── Phase 3: write output file ────────────────────────────────────────────

  const capturedAt = new Date().toISOString()

  const out = [
    `// Auto-generated by scripts/capture-alpine-snapshot.ts`,
    `// Run: npx tsx --env-file=.env.local scripts/capture-alpine-snapshot.ts`,
    `// Company: Alpine Campers  (${COMPANY_ID})`,
    `// Captured: ${capturedAt}`,
    `// Do not edit manually — re-run the capture script to refresh.`,
    ``,
    `export const ALPINE_COMPANY_ID = '${COMPANY_ID}';`,
    `export const SNAPSHOT_CAPTURED_AT = '${capturedAt}';`,
    ``,
    `// eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `export const bookings: any[] = ${JSON.stringify(bookingsRes.data, null, 2)};`,
    ``,
    `// eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `export const checklistInstances: any[] = ${JSON.stringify(instancesRes.data, null, 2)};`,
    ``,
    `// eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `export const checklistInstanceItems: any[] = ${JSON.stringify(itemsRes.data, null, 2)};`,
    ``,
    `// eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `export const checklistReopenHistory: any[] = ${JSON.stringify(historyRes.data, null, 2)};`,
    ``,
    `// eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `export const vehicleBlocks: any[] = ${JSON.stringify(blocksRes.data, null, 2)};`,
    ``,
    `// eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `export const vehicleCompliance: any[] = ${JSON.stringify(complianceRes.data, null, 2)};`,
    ``,
    `// eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `export const vehicleIssues: any[] = ${JSON.stringify(issuesRes.data, null, 2)};`,
    ``,
    `// eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `export const guestFeedback: any[] = ${JSON.stringify(feedbackRes.data, null, 2)};`,
    ``,
    `// eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `export const vehicles: any[] = ${JSON.stringify(vehiclesRes.data, null, 2)};`,
    ``,
    `// eslint-disable-next-line @typescript-eslint/no-explicit-any`,
    `export const companySettings: any[] = ${JSON.stringify(settingsRes.data, null, 2)};`,
    ``,
  ].join('\n')

  mkdirSync(dirname(OUT_PATH), { recursive: true })
  writeFileSync(OUT_PATH, out, 'utf-8')

  console.log(`\nWritten → lib/demo/alpine-snapshot.ts`)
}

main().catch((err) => { console.error(err); process.exit(1) })
