-- Migration 035: Write translated EN guest content for Epic Vans.
-- Only replaces the EN key; DE and SK are preserved via jsonb_set.

UPDATE public.company_settings
SET
  guest_content_i18n = jsonb_set(
    COALESCE(guest_content_i18n, '{}'::jsonb),
    '{EN}',
    $en${
  "before_arrival_info": "We also recommend:\r\n\r\nPlan your route and the first night’s parking spot\r\nFamiliarise yourself with the basic rules of using a campervan\r\nCheck the parking and camping regulations in the countries you’re travelling to\r\n\r\nIf you have any questions before your trip, feel free to contact us.",
  "pickup_info": "Pick-up location:\r\n\r\nEpic Vans / Epic Bazar\r\nSvätej Anny\r\n020 61 Ledničke Rovne\r\n\r\nNavigation:\r\nhttps://maps.app.goo.gl/FDkKnaR7MWZh9STSA\r\n\r\nIf you are travelling from further away or expect to be late, please let us know in advance by phone or message.\r\n\r\nAt vehicle handover we will:\r\n\r\n1. Inspect the vehicle and note any existing damage\r\n2. Record the current mileage and fuel level\r\n3. Explain how the vehicle works\r\n4. Show you how to operate the awning, tanks, gas, and other equipment\r\n5. Answer all your questions\r\n\r\nThe full handover process usually takes around 30–45 minutes, so please plan enough time.\r\n\r\nOur goal is for you to feel comfortable with the vehicle and be able to use it without any issues throughout your trip.",
  "important_before_pickup": "Valid driving licence for all drivers\r\nID card or passport\r\nNo need to print your booking confirmation\r\nThe deposit is paid at pick-up in cash or by bank transfer; a €4 fee applies for bank transfers due to transaction tax\r\nWe provide fitted sheets — please bring your own other bedding\r\nIf you expect to be late, contact us as soon as possible",
  "before_return_info": "Before returning the vehicle, please prepare it as follows:\n\nempty the chemical toilet cassette and the waste water tank\n\nrefuel with diesel close to our base, ideally in Ledničke Rovne or Púchov\n\nclean the interior and wash the exterior\n\nallow enough travel time, as a campervan drives slower than a regular car\n\nif you expect to be late or have a problem, contact us as soon as possible",
  "return_info": "Please return the vehicle to the same location where you picked it up:\r\n\r\nEpic Vans / Epic Bazar\r\nSvätej Anny\r\n020 61 Ledničke Rovne\r\n\r\nPlease allow enough time to prepare the vehicle before returning it. Incomplete cleaning, an unemptied toilet, or an unprepared vehicle can delay the return process.\r\n\r\nRefuel as close to our location as possible, ideally in Ledničke Rovne or Púchov. If you refuel too far away, the fuel gauge may drop after a short drive and cause confusion during the check.\r\n\r\nIf you don’t want to clean the vehicle yourself, professional cleaning is available. We recommend booking it in advance.\r\n\r\nIf you don’t want to buy AdBlue in a canister or pay a higher price, you may return the vehicle without topping up AdBlue. We can top it up here and charge you the actual cost.\r\n\r\nAfter your return we will inspect the vehicle together, record the mileage, and check the fuel level. The check usually takes around 15–20 minutes.",
  "included_items": "Included in the rental price:\n\nfully equipped campervan\nkitchen equipment (crockery, pots, cutlery)\nbed linen and pillows\noutdoor table and chairs\nelectric hook-up cable for campsites\nwater fill hose\nbasic vehicle equipment\n\nDepending on your booking, extras may also be available, such as:\n\npaddleboard\nelectric pump\nbadminton set\nelectric grill\ncoffee maker\n\nThe exact list of extras is shown in your booking.",
  "rules_and_tips": "Always be aware of the vehicle’s height when driving or parking\nClose the awning before driving\nMake sure all doors, windows, and roof vents are closed\nDrive slower than you would in a regular car and keep a greater following distance\nObserve the vehicle’s maximum permitted weight\n\nIf something doesn’t seem right while driving, pull over safely and contact us",
  "help_intro": "If something isn’t working, try the steps below first. If the problem persists, contact us and we’ll help you out.",
  "help_quick_fixes": "No electricity:\nCheck the battery level on the control panel\nMake sure the main switch is turned on\nIf connected to campsite electricity, check the hook-up cable\nTurn appliances off and back on\n\nWater not working:\nCheck the fresh water tank level\nTurn on the water pump\nOpen the tap and wait a few seconds\nCheck that no hose has come loose\n\nFridge not cooling:\nCheck that the fridge is set to the correct mode: 12 V, 230 V, or gas\nIf using gas, make sure the gas bottle is open\nWait 10–15 minutes for it to start cooling\nDon’t overfill the fridge\n\nHeating not working:\nCheck that the heating is switched on\nMake sure there is enough gas and battery charge\nTurn the set temperature up\nWait a few minutes for the system to start\n\nToilet problem:\nCheck the state of the toilet cassette\nIf it’s full, empty it\nAdd toilet chemical if needed\nMake sure the cassette is properly inserted\n\nGas not working:\nCheck that the gas bottle is open\nCheck that the gas valve is not closed\nTry another gas appliance\nIf you smell gas or are unsure, stop using gas and contact us\n\nWater not draining:\nCheck the waste water tank level\nEmpty it if necessary\nMake sure the drain valve is open",
  "help_videos": "Hard reset of the Truma boiler:\nhttps://youtu.be/qqp64CEdUeQ?si=rZXjDaOb1j-6JOoX",
  "faq_items": [
    {"question": "What are the cancellation conditions?", "answer": "More than 6 weeks (42+ days) before the rental start: Administrative fee €25.\n\nBetween 6 weeks (41 days) and 2 weeks (14 days) before the rental start: Cancellation fee of 50% of the total rental price.\n\nLess than 2 weeks (13 days or fewer) before the rental start: Cancellation fee of 100% of the total rental price.\n\nEpic Travel s.r.o. cannot transfer or carry over payments from one booking to another.\n"},
    {"question": "These are large vans — can I drive them?", "answer": "Yes, as long as you have two years of driving experience and are between 23 and 75 years old, you can drive our vans with a standard driving licence.\n"},
    {"question": "Is there an age restriction?", "answer": "Age 23 to 75.\n"},
    {"question": "How many people fit in the campervan?", "answer": "Ducato 250\n4 seats with seatbelts\n2+2 (sleeping places)\nSiena 395\n5 seats with seatbelts\n4+1 (sleeping places)\nSiena 385\n5 seats with seatbelts\n4+1 (sleeping places)\n"},
    {"question": "What is included in the campervan rental?", "answer": "Campervan rental.\nFully comprehensive insurance for one driver (additional drivers can be added).\nUnlimited km. (reasonable use)\nHighway vignette for SK, SI, AT.\nCamping furniture.\nCooking equipment, crockery, cutlery, camping gas.\nFull fuel tank — please return it full.\nFull water tank — no need to refill on return.\nPaddle board (for Ducato, space only if you are 2).\nBike rack for 4 bicycles.\nElectric pump.\nCoffee maker\nElectric grill"},
    {"question": "Who can drive the vehicle?", "answer": "Drivers aged 23 to 75 with a valid EU driving licence.\nThe licence must have been held for more than two years.\nWe also accept licences from non-EU countries — contact us to check if yours qualifies.\nIf you don’t meet the above criteria, contact us and we’ll try to arrange something with our insurers.\nUp to 3 additional drivers can be added.\n"},
    {"question": "When can I pick up the campervan and when must I return it?", "answer": "Pick-up: from 09:00 on the first day of your rental.\n\nReturn: by 19:00 on the last day of your rental.\n\nIf you return the vehicle later without prior agreement, it will be treated as a new rental day (a full-day charge applies).\n\n⚠ Important: The refundable deposit will not be returned immediately if the vehicle has not been cleaned inside and washed outside. Cleaning can take up to 3 hours, after which the deposit will be returned minus any agreed deductions.\n"},
    {"question": "Where can I leave my car?", "answer": "You can leave your car in our car park free of charge. The car park has cameras, but you leave your vehicle there at your own risk. For those who live nearby, we can arrange a driver pick-up."},
    {"question": "Is it a manual or automatic gearbox?", "answer": "Ducato 250 - manual gearbox\nSiena 395 - automatic gearbox\nSiena 385 - manual gearbox"},
    {"question": "What about fuel?", "answer": "All vehicles run on diesel. You will receive a full tank of fuel at pick-up and must return it with a full tank."},
    {"question": "Can we bring children?", "answer": "Yes, of course! All seats are fitted with three-point seatbelts for maximum safety.\n\nThe Siena 385 and Siena 395 have ISOFIX anchor points, making it easy and safe to attach ISOFIX child seats.\n\n⚠ Note: The Ducato 250 does not have ISOFIX anchor points, so child seats must be secured using standard seatbelts.\n"},
    {"question": "What about pets?", "answer": "Yes, pets are welcome! We do charge a €30 cleaning fee to cover a deep clean after your stay.\n\nPlease keep pets off the sofa and beds, as we want to protect customers with allergies and prevent hair getting into soft furnishings.\n"},
    {"question": "Is it cold in the van?", "answer": "No, all vans are fitted with heaters that can be used throughout the night and day. So even in the depths of winter you’ll be perfectly comfortable and warm."},
    {"question": "Do I need an electricity hook-up?", "answer": "Ideally yes — we recommend campsites with an electric hook-up.\n\nOur vans do have a solar system, and the battery also charges while the engine is running. In good sunny weather they can keep the lights on and charge all phones.\n\n⚠ Important: The 220V socket and the air conditioning in the living area will not work unless the vehicle is connected to an external 220V power source.\n\nException: The Ducato 250 is better suited to longer off-grid stays. It has Smart Maxxair fans powered by the battery, a significantly larger solar system, and a bigger battery, allowing for longer stays without needing an external power source.\n"},
    {"question": "Can I smoke in the rented vehicle / campervan?", "answer": "Smoking (and vaping) is not permitted in our vehicles. If evidence of smoking is found, the full cleaning fee will be deducted from the security deposit."},
    {"question": "How can I book and pay?", "answer": "Go to the rental page.\nRequest a booking for your dates.\nWe will confirm your booking.\nPay by bank transfer.\n"},
    {"question": "Do I need to pay a deposit?", "answer": "Yes, a security deposit must be paid before the rental begins:\nCampervan rental: deposit €1,000\n\nThe deposit covers the insurance excess in the unlikely event of an accident and any potential damage to the vehicle, accessories, or equipment during the rental.\n\nThe deposit will be returned minus the cost of any repairs, replacements, fuel top-up, or cleaning. An invoice with a detailed breakdown of costs will be issued for any deductions.\n"},
    {"question": "What is the fuel consumption (l/100 km)?", "answer": "Fuel consumption depends on your driving style, terrain, and vehicle load. The average consumption according to the manual is:\n\nDucato 250 - 10 l/100 km\nSiena 395 - 11 l/100 km\nSiena 385 - 11 l/100 km\n\nActual consumption may vary slightly depending on driving conditions.\n"},
    {"question": "Is the vehicle equipped with a GPS tracking device?", "answer": "Yes, this is for security reasons."},
    {"question": "Do you accept cryptocurrencies?", "answer": "EpicVans now accepts payments in Bitcoin (BTC) and Ethereum (ETH). The amount on the invoice will be calculated at the current exchange rate at the time of payment, based on a trusted market source. The rate will be locked when the invoice is issued to ensure a fair and transparent transaction for both parties."}
  ]
}$en$::jsonb
  ),
  updated_at = now()
WHERE name = 'Epic Vans';

-- Verify
SELECT
  lang,
  field_key,
  left(field_val, 80) AS preview
FROM public.company_settings,
  jsonb_each(COALESCE(guest_content_i18n, '{}'::jsonb))  AS l(lang, lang_obj),
  jsonb_each_text(lang_obj)                              AS f(field_key, field_val)
WHERE name = 'Epic Vans'
  AND lang IN ('EN', 'SK', 'DE')
  AND field_key != 'faq_items'
ORDER BY lang, field_key;
