-- Migration 036: Write translated DE guest content for Epic Vans.
-- Only replaces the DE key; EN and SK are preserved via jsonb_set.

UPDATE public.company_settings
SET
  guest_content_i18n = jsonb_set(
    COALESCE(guest_content_i18n, '{}'::jsonb),
    '{DE}',
    $de${
  "before_arrival_info": "Wir empfehlen außerdem:\r\n\r\nPlanen Sie Ihre Route und den ersten Übernachtungsplatz\r\nMachen Sie sich mit den grundlegenden Regeln für die Nutzung eines Campervans vertraut\r\nInformieren Sie sich über die Park- und Campingvorschriften in den Ländern, die Sie bereisen\r\n\r\nWenn Sie vor Ihrer Reise Fragen haben, können Sie uns jederzeit kontaktieren.",
  "pickup_info": "Abholort:\r\n\r\nEpic Vans / Epic Bazar\r\nSvätej Anny\r\n020 61 Lednické Rovne\r\n\r\nNavigation:\r\nhttps://maps.app.goo.gl/FDkKnaR7MWZh9STSA\r\n\r\nWenn Sie von weiter entfernt anreisen oder mit einer Verspätung rechnen, informieren Sie uns bitte im Voraus telefonisch oder per Nachricht.\r\n\r\nBei der Fahrzeugübergabe werden wir gemeinsam:\r\n\r\n1. Das Fahrzeug inspizieren und vorhandene Schäden dokumentieren\r\n2. Den aktuellen Kilometerstand und den Tankfüllstand festhalten\r\n3. Die Funktionsweise des Fahrzeugs erklären\r\n4. Die Bedienung der Markise, Tanks, Gasanlage und weiterer Ausstattung zeigen\r\n5. Alle Ihre Fragen beantworten\r\n\r\nDie gesamte Übergabe dauert in der Regel etwa 30–45 Minuten – planen Sie daher bitte ausreichend Zeit ein.\r\n\r\nUnser Ziel ist es, dass Sie sich mit dem Fahrzeug wohlfühlen und es während Ihrer gesamten Reise problemlos nutzen können.",
  "important_before_pickup": "Gültiger Führerschein aller Fahrer\r\nPersonalausweis oder Reisepass\r\nDie Buchungsbestätigung muss nicht ausgedruckt werden\r\nDie Kaution wird bei der Abholung in bar oder per Banküberweisung bezahlt; bei Banküberweisung fällt eine Gebühr von 4 € wegen der Transaktionssteuer an\r\nWir stellen Spannbettlaken zur Verfügung – bitte bringen Sie Ihre eigene weitere Bettwäsche mit\r\nWenn Sie mit Verspätung rechnen, kontaktieren Sie uns bitte so früh wie möglich",
  "before_return_info": "Bitte bereiten Sie das Fahrzeug vor der Rückgabe wie folgt vor:\n\nKassette der Chemietoilette und den Abwassertank leeren\n\nDiesel möglichst nah an unserer Basis nachtanken, idealerweise in Lednické Rovne oder Púchov\n\nInnenraum reinigen und Fahrzeug außen waschen\n\nAusreichend Fahrzeit einplanen, da ein Campervan langsamer fährt als ein normales Auto\n\nWenn Sie mit Verspätung rechnen oder ein Problem haben, kontaktieren Sie uns so früh wie möglich",
  "return_info": "Bitte geben Sie das Fahrzeug an demselben Ort zurück, an dem Sie es abgeholt haben:\r\n\r\nEpic Vans / Epic Bazar\r\nSvätej Anny\r\n020 61 Lednické Rovne\r\n\r\nBitte planen Sie ausreichend Zeit für die Vorbereitung des Fahrzeugs vor der Rückgabe ein. Unvollständige Reinigung, eine nicht entleerte Toilette oder ein unvorbereitetes Fahrzeug können den Rückgabeprozess verzögern.\r\n\r\nTanken Sie so nah wie möglich an unserem Standort, idealerweise in Lednické Rovne oder Púchov. Wenn Sie zu weit weg tanken, kann die Tankanzeige nach kurzer Fahrt sinken und bei der Überprüfung zu Missverständnissen führen.\r\n\r\nWenn Sie das Fahrzeug nicht selbst reinigen möchten, steht eine professionelle Reinigung zur Verfügung. Wir empfehlen, diese im Voraus zu buchen.\r\n\r\nWenn Sie kein AdBlue in einem Kanister kaufen oder einen höheren Preis zahlen möchten, können Sie das Fahrzeug auch ohne AdBlue-Nachfüllung zurückgeben. Wir können es hier auffüllen und berechnen Ihnen die tatsächlichen Kosten.\r\n\r\nNach der Rückgabe überprüfen wir gemeinsam den Fahrzeugzustand, erfassen den Kilometerstand und prüfen den Tankfüllstand. Die Kontrolle dauert in der Regel etwa 15–20 Minuten.",
  "included_items": "Im Mietpreis enthalten:\n\nvoll ausgestatteter Campervan\nKüchenausstattung (Geschirr, Töpfe, Besteck)\nBettwäsche und Kissen\nAußentisch und Stühle\nElektrokabel für den Campingplatzanschluss\nWasserschlauch zum Befüllen\ngrundlegende Fahrzeugausstattung\n\nJe nach Buchung können auch Extras verfügbar sein, wie z. B.:\n\nPaddleboard\nelektrische Pumpe\nBadminton-Set\nelektrischer Grill\nKaffeemaschine\n\nDie genaue Liste der Extras ist in Ihrer Buchung angegeben.",
  "rules_and_tips": "Achten Sie beim Fahren und Parken stets auf die Fahrzeughöhe\nMarkise vor der Abfahrt einfahren\nStellen Sie sicher, dass alle Türen, Fenster und Dachluken geschlossen sind\nFahren Sie langsamer als mit einem normalen Auto und halten Sie mehr Abstand\nBeachten Sie das zulässige Gesamtgewicht des Fahrzeugs\n\nWenn beim Fahren etwas nicht stimmt, halten Sie sicher an und kontaktieren Sie uns",
  "help_intro": "Wenn etwas nicht funktioniert, versuchen Sie zunächst die folgenden Schritte. Wenn das Problem weiterhin besteht, kontaktieren Sie uns und wir helfen Ihnen.",
  "help_quick_fixes": "Kein Strom:\nAkkuladestand am Bedienfeld prüfen\nSicherstellen, dass der Hauptschalter eingeschaltet ist\nBei Anschluss an Campingplatzelektrizität das Anschlusskabel prüfen\nGeräte aus- und wieder einschalten\n\nWasser funktioniert nicht:\nFüllstand des Frischwassertanks prüfen\nWasserpumpe einschalten\nHahn öffnen und einige Sekunden warten\nPrüfen, ob ein Schlauch gelöst ist\n\nKühlschrank kühlt nicht:\nPrüfen, ob der Kühlschrank auf den richtigen Modus eingestellt ist: 12 V, 230 V oder Gas\nBei Gasbetrieb sicherstellen, dass die Gasflasche geöffnet ist\n10–15 Minuten warten, bis er zu kühlen beginnt\nKühlschrank nicht überfüllen\n\nHeizung funktioniert nicht:\nPrüfen, ob die Heizung eingeschaltet ist\nSicherstellen, dass genug Gas und Akkukapazität vorhanden ist\nSolltemperatur erhöhen\nEinige Minuten warten, bis das System startet\n\nToilettenproblem:\nZustand der Toilettenkassette prüfen\nWenn sie voll ist, entleeren\nBei Bedarf Toilettenchemie hinzufügen\nSicherstellen, dass die Kassette richtig eingesetzt ist\n\nGas funktioniert nicht:\nPrüfen, ob die Gasflasche geöffnet ist\nPrüfen, ob das Gasventil nicht geschlossen ist\nEin anderes Gasgerät ausprobieren\nWenn Sie Gas riechen oder unsicher sind, Gas nicht mehr verwenden und uns kontaktieren\n\nWasser läuft nicht ab:\nFüllstand des Abwassertanks prüfen\nBei Bedarf entleeren\nSicherstellen, dass das Ablassventil geöffnet ist",
  "help_videos": "Werksreset des Truma-Boilers:\nhttps://youtu.be/qqp64CEdUeQ?si=rZXjDaOb1j-6JOoX",
  "faq_items": [
    {"question": "Was sind die Stornierungsbedingungen?", "answer": "Mehr als 6 Wochen (42+ Tage) vor Mietbeginn: Verwaltungsgebühr 25 €.\n\nZwischen 6 Wochen (41 Tage) und 2 Wochen (14 Tage) vor Mietbeginn: Stornogebühr von 50 % des Gesamtmietpreises.\n\nWeniger als 2 Wochen (13 Tage oder weniger) vor Mietbeginn: Stornogebühr von 100 % des Gesamtmietpreises.\n\nEpic Travel s.r.o. kann Zahlungen nicht von einer Buchung auf eine andere übertragen.\n"},
    {"question": "Das sind große Vans – kann ich sie fahren?", "answer": "Ja, solange Sie zwei Jahre Fahrerfahrung haben und zwischen 23 und 75 Jahre alt sind, können Sie unsere Vans mit einem normalen Führerschein fahren.\n"},
    {"question": "Gibt es eine Altersbeschränkung?", "answer": "Alter 23 bis 75 Jahre.\n"},
    {"question": "Wie viele Personen passen in den Campervan?", "answer": "Ducato 250\n4 Sitzplätze mit Sicherheitsgurten\n2+2 (Schlafplätze)\nSiena 395\n5 Sitzplätze mit Sicherheitsgurten\n4+1 (Schlafplätze)\nSiena 385\n5 Sitzplätze mit Sicherheitsgurten\n4+1 (Schlafplätze)\n"},
    {"question": "Was ist in der Campervvan-Miete enthalten?", "answer": "Campervan-Miete.\nVollkaskoversicherung für einen Fahrer (weitere Fahrer können hinzugefügt werden).\nUnbegrenzte km. (angemessene Nutzung)\nAutobahnvignette für SK, SI, AT.\nCampingmöbel.\nKochausstattung, Geschirr, Besteck, Campinggas.\nVoller Kraftstofftank – bitte voll zurückgeben.\nVoller Wassertank – bei der Rückgabe muss nicht nachgefüllt werden.\nPaddleboard (beim Ducato nur Platz für 2 Personen).\nFahrradträger für 4 Fahrräder.\nElektrische Pumpe.\nKaffeemaschine\nElektrischer Grill"},
    {"question": "Wer darf das Fahrzeug fahren?", "answer": "Fahrer im Alter von 23 bis 75 Jahren mit gültigem EU-Führerschein.\nDer Führerschein muss seit mehr als zwei Jahren besessen werden.\nWir akzeptieren auch Führerscheine aus Nicht-EU-Ländern – kontaktieren Sie uns, um zu prüfen, ob Ihrer in Frage kommt.\nWenn Sie die oben genannten Kriterien nicht erfüllen, kontaktieren Sie uns und wir werden versuchen, mit unseren Versicherern eine Lösung zu finden.\nBis zu 3 weitere Fahrer können hinzugefügt werden.\n"},
    {"question": "Wann kann ich den Campervan abholen und wann muss ich ihn zurückgeben?", "answer": "Abholung: ab 09:00 Uhr am ersten Tag Ihrer Miete.\n\nRückgabe: bis 19:00 Uhr am letzten Tag Ihrer Miete.\n\nWenn Sie das Fahrzeug später ohne vorherige Absprache zurückgeben, wird dies als neuer Miettag gewertet (es wird eine ganztägige Gebühr berechnet).\n\n⚠ Wichtig: Die rückerstattbare Kaution wird nicht sofort zurückgegeben, wenn das Fahrzeug nicht innen gereinigt und außen gewaschen wurde. Die Reinigung kann bis zu 3 Stunden dauern, danach wird die Kaution abzüglich vereinbarter Abzüge zurückerstattet.\n"},
    {"question": "Wo kann ich mein Auto lassen?", "answer": "Sie können Ihr Auto kostenlos auf unserem Parkplatz abstellen. Der Parkplatz ist videoüberwacht, aber Sie lassen Ihr Fahrzeug auf eigene Gefahr dort. Für Gäste aus der näheren Umgebung können wir eine Fahrerabholung organisieren."},
    {"question": "Ist es ein Schalt- oder Automatikgetriebe?", "answer": "Ducato 250 - Schaltgetriebe\nSiena 395 - Automatikgetriebe\nSiena 385 - Schaltgetriebe"},
    {"question": "Was ist mit dem Kraftstoff?", "answer": "Alle Fahrzeuge fahren mit Diesel. Sie erhalten bei der Abholung einen vollen Tank und müssen das Fahrzeug mit vollem Tank zurückgeben."},
    {"question": "Können wir Kinder mitbringen?", "answer": "Ja, natürlich! Alle Sitze sind mit Dreipunkt-Sicherheitsgurten für maximale Sicherheit ausgestattet.\n\nDie Siena 385 und Siena 395 haben ISOFIX-Befestigungspunkte, sodass ISOFIX-Kindersitze einfach und sicher befestigt werden können.\n\n⚠ Hinweis: Der Ducato 250 hat keine ISOFIX-Befestigungspunkte, daher müssen Kindersitze mit normalen Sicherheitsgurten gesichert werden.\n"},
    {"question": "Was ist mit Haustieren?", "answer": "Ja, Haustiere sind willkommen! Wir berechnen jedoch eine Reinigungsgebühr von 30 € für eine Grundreinigung nach Ihrem Aufenthalt.\n\nBitte halten Sie Haustiere von Sofa und Betten fern, da wir Kunden mit Allergien schützen und verhindern möchten, dass Haare in die Polster gelangen.\n"},
    {"question": "Ist es kalt im Van?", "answer": "Nein, alle Vans sind mit Heizungen ausgestattet, die rund um die Uhr genutzt werden können. Selbst im tiefsten Winter sind Sie also bestens versorgt und warm."},
    {"question": "Brauche ich einen Stromanschluss?", "answer": "Idealerweise ja – wir empfehlen Campingplätze mit Stromanschluss.\n\nUnsere Vans haben jedoch ein Solarsystem, und die Batterie lädt auch während der Fahrt mit dem Motor. Bei gutem Sonnenwetter können die Lichter eingeschaltet bleiben und alle Handys aufgeladen werden.\n\n⚠ Wichtig: Die 220V-Steckdose und die Klimaanlage im Wohnbereich funktionieren nicht, wenn das Fahrzeug nicht an eine externe 220V-Stromquelle angeschlossen ist.\n\nAusnahme: Der Ducato 250 eignet sich besser für längere Aufenthalte abseits des Stromnetzes. Er hat batteriebetriebene Smart Maxxair-Lüfter, ein deutlich größeres Solarsystem und eine größere Batterie, was längere Aufenthalte ohne externe Stromquelle ermöglicht.\n"},
    {"question": "Darf ich im gemieteten Fahrzeug / Campervan rauchen?", "answer": "Rauchen (und Dampfen) ist in unseren Fahrzeugen nicht gestattet. Wenn Spuren von Rauchen gefunden werden, wird die vollständige Reinigungsgebühr von der Kaution abgezogen."},
    {"question": "Wie kann ich buchen und bezahlen?", "answer": "Gehen Sie zur Mietseite.\nStellen Sie eine Buchungsanfrage für Ihre Termine.\nWir bestätigen Ihre Buchung.\nZahlen Sie per Banküberweisung.\n"},
    {"question": "Muss ich eine Kaution hinterlegen?", "answer": "Ja, vor Mietbeginn muss eine Sicherheitskaution bezahlt werden:\nCampervan-Miete: Kaution 1.000 €\n\nDie Kaution deckt den Versicherungsselbstbehalt im unwahrscheinlichen Fall eines Unfalls sowie mögliche Schäden am Fahrzeug, Zubehör oder Ausstattung während der Miete ab.\n\nDie Kaution wird abzüglich der Kosten für Reparaturen, Ersatz, Kraftstoffnachfüllung oder Reinigung zurückerstattet. Für etwaige Abzüge wird eine Rechnung mit detaillierter Kostenaufstellung ausgestellt.\n"},
    {"question": "Wie hoch ist der Kraftstoffverbrauch (l/100 km)?", "answer": "Der Kraftstoffverbrauch hängt von Ihrem Fahrstil, dem Gelände und der Fahrzeugbeladung ab. Der durchschnittliche Verbrauch laut Handbuch beträgt:\n\nDucato 250 - 10 l/100 km\nSiena 395 - 11 l/100 km\nSiena 385 - 11 l/100 km\n\nDer tatsächliche Verbrauch kann je nach Fahrbedingungen leicht abweichen.\n"},
    {"question": "Ist das Fahrzeug mit einem GPS-Tracker ausgestattet?", "answer": "Ja, das ist aus Sicherheitsgründen so."},
    {"question": "Akzeptieren Sie Kryptowährungen?", "answer": "EpicVans akzeptiert jetzt Zahlungen in Bitcoin (BTC) und Ethereum (ETH). Der Rechnungsbetrag wird zum aktuellen Wechselkurs zum Zeitpunkt der Zahlung berechnet, basierend auf einer vertrauenswürdigen Marktquelle. Der Kurs wird bei Rechnungsstellung festgeschrieben, um eine faire und transparente Transaktion für beide Parteien zu gewährleisten."}
  ]
}$de$::jsonb
  ),
  updated_at = now()
WHERE name = 'Epic Vans';

-- Verify
SELECT
  lang,
  field_key,
  left(field_val, 80) AS preview
FROM public.company_settings,
  jsonb_each(COALESCE(guest_content_i18n, '{}'::jsonb))  AS l(lang, lang_obj),
  jsonb_each_text(lang_obj)                              AS f(field_key, field_val)
WHERE name = 'Epic Vans'
  AND lang IN ('EN', 'SK', 'DE')
  AND field_key != 'faq_items'
ORDER BY lang, field_key;
